workflow cleanup in progress

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -5,6 +5,8 @@ on:
   pull_request:
   merge_group:
     branches: [main, feature/poA-consensus]
+  push:
+    branches: [feature/poA-consensus]
 
 env:
   CARGO_TERM_COLOR: always
@@ -63,49 +65,57 @@ jobs:
           --bitcoind-user ${{env.BITCOIND_USER}} \
           --bitcoind-pass ${{ env.BITCOIND_PASS }} \
           --min-signers 3 \
-          --max-signers 4 & 
-          sleep 600
-          echo "e2e tests completed successfully!"
+          --max-signers 4 
 
-  test:
-    name: test / ethereum
-    runs-on: botanix-actions-runner-vm-1
-    env:
-      RUST_BACKTRACE: 1
-    timeout-minutes: 60
-    steps:
-      - uses: actions/checkout@v4
+          if [ $? -eq 0 ]; then
+            echo "e2e tests completed successfully, exiting..."
+            exit 0
+          else
+            echo "Btc-server did not run successfully."
+            exit 1
+          fi
 
-      - run: /home/runner/.cargo/bin/rustup toolchain install stable --profile minimal
+  # This performs the same test as the e2e job, but only on btc_server
+  # test:
+  #   name: test / ethereum
+  #   runs-on: botanix-actions-runner-vm-1
+  #   env:
+  #     RUST_BACKTRACE: 1
+  #   timeout-minutes: 60
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - uses: Swatinem/rust-cache@v2
-        with:
-          cache-on-failure: true
-          cache-all-crates: true
+  #     - run: /home/runner/.cargo/bin/rustup toolchain install stable --profile minimal
 
-      - name: Start BTC Server
-        run: |
-          cd ./bin/btc-server && \
-          /home/runner/.cargo/bin/cargo run --bin btc-server -- \
-          --identifier 0 \
-          --address 0.0.0.0:8080 \
-          --db "./db1" \
-          --min-signers 2 \
-          --max-signers 2 \
-          --toml ./config.toml \
-          --fee-rate-diff-percentage 30 \
-          --btc-network ${{env.BITCOIND_NETWORK}} \
-          --bitcoind-url ${{env.BITCOIND_URL}} \
-          --bitcoind-user ${{env.BITCOIND_USER}} \
-          --bitcoind-pass ${{ env.BITCOIND_PASS }} \
-          --fall-back-fee-rate-sat-per-vbyte 5 &
-          pid=$! 
-          sleep 150
-          echo "Killing BTC Server"
-          kill -9 $pid
+  #     - uses: Swatinem/rust-cache@v2
+  #       with:
+  #         cache-on-failure: true
+  #         cache-all-crates: true
+
+  #     - name: Start BTC Server
+  #       run: |
+  #         cd ./bin/btc-server && \
+  #         /home/runner/.cargo/bin/cargo run --bin btc-server -- \
+  #         --identifier 0 \
+  #         --address 0.0.0.0:8080 \
+  #         --db "./db1" \
+  #         --min-signers 2 \
+  #         --max-signers 2 \
+  #         --toml ./config.toml \
+  #         --fee-rate-diff-percentage 30 \
+  #         --btc-network ${{env.BITCOIND_NETWORK}} \
+  #         --bitcoind-url ${{env.BITCOIND_URL}} \
+  #         --bitcoind-user ${{env.BITCOIND_USER}} \
+  #         --bitcoind-pass ${{ env.BITCOIND_PASS }} \
+  #         --fall-back-fee-rate-sat-per-vbyte 5 &
+  #         pid=$! 
+  #         sleep 150
+  #         echo "Killing BTC Server"
+  #         kill -9 $pid
 
   sync:
     name: sync / 100k blocks
+    if: github.event_name == 'merge_group'
     runs-on: botanix-actions-runner-vm-1
     env:
       RUST_LOG: info,sync=error
@@ -141,3 +151,6 @@ jobs:
           sleep 150
           echo "Killing BTC Server"
           kill -9 $pid
+
+
+          
